Add: 로그인/회원가입 구현완료
wecode-bootcamp-korea/15-2nd-CodeBnB-backend pull request #3
Opened 2021-01-03 09:53 UTC by markiron99

- 회원가입 앤드 포인트 및 정규표현식 적용
- 카카오/일반 로그인 앤드포인트 구현완료
- 기타 예외 처리 완료

2021-01-04 02:37 UTC, jamessoun93 requested changes

2021-01-04 02:37 UTC, jamessoun93 commented on users/utils.py
> +    return wrapper
중복되는 코드인데 데코레이터가 두개로 분리되어있네요? 어떤 목적이신가요?

2021-01-04 02:37 UTC, jamessoun93 commented on users/views.py
> +from django.shortcuts       import render
불필요합니다.

2021-01-04 02:37 UTC, jamessoun93 commented on users/views.py
> +            birth           = date(int(data["birthdayYear"]), int(data["birthdayMonth"]), int(data["birthdayDate"]))
이렇게 다 따로 받으시지 말고 "YYYY-MM-DD" 형식으로 문자열로 받으시는게 처리하기 편하실텐데요!

2021-01-04 02:37 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({"MESSAGE" : "INVALID_BIRTHDAY"})
둘다 `KeyError` 를 확인하는 조건인데 메세지랑 매칭이 잘 안되네요. 키에러 목적이시면 이렇게 if 문까지 만들어주실 필요는 없습니다.

2021-01-04 02:37 UTC, jamessoun93 commented on users/views.py
> +            cryped_password = hashed_password.decode("utf-8")
cryped -> 오타입니다. 더 정확한 표현으로 변경해주세요.

2021-01-04 02:37 UTC, jamessoun93 commented on users/views.py
> +                    birthday        = birth.isoformat(),
birthday를 애초에 "YYYY-MM-DD" 형식으로 받으신다면 여기서 이렇게 처리해주실 필요가 없겠죠!?

2021-01-04 02:37 UTC, jamessoun93 commented on users/views.py
> +class KakaoSignInView(View):
이렇게 있으면 가져오고 없으면 생성하는 로직에서는 `get_or_create()` 메서드를 활용하시면 코드가 간결해집니다 👍

2021-01-04 02:37 UTC, jamessoun93 commented on users/views.py
> +            email   = data.get("email")
여기서 `.get()`을 사용하신 이유가 무엇인가요?

2021-01-04 02:56 UTC, markiron99 commented on users/views.py
> +                return JsonResponse({"MESSAGE" : "INVALID_BIRTHDAY"})
시험하는 과정에서 어떤 부분 때문에 에러가 발생한 것인지 확인하기 위한 목적으로 기재해두었습니다!
추후 merge되는 버전에서는 수정 반영 하겠습니다!

2021-01-04 02:57 UTC, markiron99 commented on users/views.py
> +                    birthday        = birth.isoformat(),
프론트 분과 협의하는 과정에서 따로따로 받기로 하고 진행했는데
이미 강을 건너간 것 같습니다.. 합쳐서 받으면 됐었는데..

2021-01-04 02:59 UTC, markiron99 commented on users/views.py
> +from django.shortcuts       import render
수정하겠습니다!

2021-01-04 02:59 UTC, markiron99 commented on users/views.py
> +            birth           = date(int(data["birthdayYear"]), int(data["birthdayMonth"]), int(data["birthdayDate"]))
프론트 분과 협의하는 과정에서 따로따로 받기로 하고 진행했는데
이미 강을 건너간 것 같습니다.. 합쳐서 받으면 됐었는데..

2021-01-04 03:06 UTC, markiron99 commented on users/views.py
> +            cryped_password = hashed_password.decode("utf-8")
수정하겠습니다!

2021-01-04 11:29 UTC, markiron99 commented on users/views.py
> +            email   = data.get("email")
현재 로그인 로직의 경우 email 데이터가 없을 때는 키 에러가 발생이 되도록 data['email'] 을 사용해야 하는데,
데이터가 없는 경우 None이 출력되는 .get('email')을 사용했다는 점에 있어 오용을 한 것 같습니다.

처음엔
data = json.loads(request.body)를 선언한 후에
data['email'] 로 받아오는 것과 .get() 과 차이가 크게 없다고 생각했었는데, 
공부를 해보니 제 무지를 깨닫게 해주신 점 감사드립니다,,,

바로 수정하겠습니다.

2021-01-04 11:29 UTC, markiron99 commented on users/utils.py
> +    return wrapper
CheckLogin -> 유저가 로그인이 필수인 페이지로 접근할 때 필요한 데코레이터 입니다. (ex: 예약, 결제, 호스트 등..)

CheckUser -> 유저가 로그인과 관계없는 자원에 접근을 한 상태에서 이 유저가 어떤 유저인지 구분하기 위하여 만든 데코레이터 입니다!

2021-01-04 12:08 UTC, markiron99 commented on users/views.py
> +                return JsonResponse({"MESSAGE" : "INVALID_BIRTHDAY"})
name의 경우 빈칸(스페이스바)으로 작성하는 경우가 있을 수 있어 남겨두고,
생년월일은 삭제하겠습니다!

2021-01-05 10:19 UTC, markiron99 commented on users/views.py
> +class KakaoSignInView(View):
수정 반영 했습니다...!

2021-01-05 11:17 UTC, ulfrid requested changes
수정 부탁드립니다.

2021-01-05 11:17 UTC, ulfrid commented on users/models.py
> +    password            = models.CharField(max_length=256,default="a123456789")
이건 왜 하시는거죠?  보안에 정말 취약한것 같은데요~!
```suggestion
    password            = models.CharField(max_length=256)
```

2021-01-05 11:17 UTC, ulfrid commented on users/models.py
> +    birthday            = models.DateField(null=True,default="2020-12-31")
```suggestion
    birthday            = models.DateField(null=True)
```
왜 특정 일자를 디폴트로 넣으시는거죠?

2021-01-05 13:14 UTC, markiron99 commented on users/views.py
> +class KakaoSignInView(View):
get_or_create로 진행했었으나..
완벽하게 이해하고 구현을 하지 못해서
models.py쪽에 심각한 보안 이슈를 만들었습니다.
기존 방식으로 롤백하였고,
더욱 완벽하게 이해해서 다시 구현 예정입니다..

2021-01-05 13:15 UTC, markiron99 commented on users/models.py
> +    password            = models.CharField(max_length=256,default="a123456789")
get_or_create 방식의 이해부족으로 인하여
심각한 보안 이슈를 만들었습니다.

기존 방식으로 롤백하였고, 더욱 확실하게 이해한 뒤에 다시 구현하겠습니다.

2021-01-05 13:18 UTC, markiron99 commented on users/models.py
> +    birthday            = models.DateField(null=True,default="2020-12-31")
get_or_create 방식으로 소셜로그인 구현하였으나
기존 회원가입 시 받아야 하는 정보들을 전부 받지 않는 경우 문제가 발생해서
카카오 회원가입시 받지 않는 정보에 대해서 디폴트 값을 주었습니다.

password 부분에 null=True를 주고 진행하였으나, 500에러가 발생하여
기존 방식으로 롤백하였습니다.

더욱 확실하게 익힌 뒤 다시 구현하겠습니다.

2021-01-05 14:11 UTC, ulfrid commented
LGTM.

2021-01-05 14:11 UTC, merged