Add: 숙소 리스트 & 상세페이지 조회 앤드포인트 구현
wecode-bootcamp-korea/15-2nd-CodeBnB-backend pull request #4
Opened 2021-01-03 11:33 UTC by seungjaekim-git

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 숙소 리스트 & 상세페이지 조회 앤드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 숙소 리스트 조회 기능 추가
- 페이지네이션 추가
- 필터링 옵션 추가 (대여유형,건물유형,1박요금,날짜 및 기타 등등)
- 숙소 상세페이지 조회 기능 추가
- 예외 처리 완료

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 북마크 기능이 추가되면 리스트 데이터와 상세정보에 북마크 유무 정보가 추가될것입니다. 
- 날짜 필터링 기능이 완전하지 않습니다. 제가 생각한 로직을 구현할려니 너무 서버에 부담을 주는 작업인거 같아서 정확성을 조금 줄이더라도 서버의 부담을 줄이는 방식으로 구현했습니다. 나중에 혹시 제 로직에 대해서 질문할 수 있는 시간이 있었으면 합니다 ㅠ 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-04 02:49 UTC, jamessoun93 commented
@seungjaekim-git 리뷰는 점심시간 후에 바로 이어서 진행하겠습니다~

2021-01-04 06:11 UTC, jamessoun93 requested changes

2021-01-04 06:11 UTC, jamessoun93 commented on homes/tests.py
> +        self.assertEqual(response.status_code, 404)
이렇게 매번 Client 인스턴스를 생성해주실 필요 없이 최초에 1회 해주신다음 해당 client 를 재사용 하시는게 더 효율적입니다.

2021-01-04 06:11 UTC, jamessoun93 commented on homes/views.py
> +            homes = homes.filter(facility=facility)
만약 `facility=[1,2,3,4,5]` 일 경우 첫 번째 `loop` 에서 `facility_id=1` 인경우를 필터해가지고 온 뒤부터 2,3,4,5 를 필터를 걸게되면 아무것도 잡히는게 없을텐데 어떤 의도로 작성하신건지 궁금합니다.

2021-01-04 06:11 UTC, jamessoun93 commented on homes/views.py
> +            homes  = homes.filter(query3)
이 부분은 위 Q 객체 조합하는 과정과 다르게 따로 Q 객체 만들어주신 후 바로 filter 를 하시는 이유가 있나요?

2021-01-04 06:11 UTC, jamessoun93 commented on homes/views.py
> +            end_date    = datetime.datetime.strptime(end_date,"%Y/%m/%d")
프론트에서 보내줄때부터 "YYYY-MM-DD" 포맷에 맞게 보내달라고 요청해주시면 이런 불필요한 코드가 필요없어지게 됩니다. 협의 후 적용해주세요 :)

2021-01-04 06:17 UTC, jamessoun93 requested changes

2021-01-04 06:17 UTC, jamessoun93 commented on homes/views.py
> +            Reservation = Reservation.objects.select_related("home").get(id=reservation_pk)
변수명을 이렇게 지어주시면 클래스로 착각할 가능성이 높습니다. 변경해주세요!

2021-01-04 06:17 UTC, jamessoun93 commented on homes/views.py
> +                data["rules"].append({"category":key,"rule_list":rule_list[key]})
이 부분 한번 설명해주실 수 있을까요?

2021-01-04 07:07 UTC, seungjaekim-git commented on homes/views.py
> +            Reservation = Reservation.objects.select_related("home").get(id=reservation_pk)
넵넵 !
:+1:

2021-01-04 07:33 UTC, seungjaekim-git commented on homes/views.py
> +                data["rules"].append({"category":key,"rule_list":rule_list[key]})
**체크인/체크아웃**
이 부분은 제가 모델링을 짜면서 실수한 부분입니다. ㅠ 숙소의 체크인/체크아웃 시간을 숙소규칙이라는 중간테이블에 넣었습니다. 그래서 숙소와 규칙의 중앙테이블에서 이름을 체크해서 "체크인"이라면 그 row에만 해당 숙소의 체크인 시간이 들어있어서 그 데이터를 뽑아올려고 했습니다. 그냥 숙소 테이블에 넣었으면 간단했을텐데... 라고 후회중입니다
**프론트분들이 원하는 데이터 형식**
![image](https://user-images.githubusercontent.com/69844464/103510720-1f823a80-4ea9-11eb-969d-dbb120f51946.png)

프론트 분들이 요청하신 데이터 형식이 각 rule_type에 한개당 그 type에 대한 해당하는 rule_list를 아래와 같이 불러오는 것이였습니다. 로직을 구상하다가 숙소와 규칙의 중간테이블에서 에서 rule_type을 검사하고, 그것을 딕셔너리형태로 {"숙소이용규칙" : [규칙1,규칙2,규칙3...]} 만들고, 해당 key와 value로 data에 넣는 로직으로 만들었습니다.

![image](https://user-images.githubusercontent.com/69844464/103511286-18a7f780-4eaa-11eb-997e-d1d90d9ebef4.png)

2021-01-04 07:34 UTC, seungjaekim-git commented on homes/views.py
> +            end_date    = datetime.datetime.strptime(end_date,"%Y/%m/%d")
넵넵 ! 날짜 필터링은 아직 담당 프론트분이 못 끝내셔서 맞출때 포멧에 맞춰서 맞게 보내주시라고 요청하겠습니다 ! :+1:

2021-01-04 07:40 UTC, seungjaekim-git commented on homes/tests.py
> +        self.assertEqual(response.status_code, 404)
넵 ! :+1: 감사합니다 !

2021-01-04 10:41 UTC, seungjaekim-git commented on homes/views.py
> +            homes  = homes.filter(query3)
이 부분은 제가 실수한 부분인거 같습니다. 딱히 따로 Q 객체로 빼서 구현을 안해도 되는군요.
```python
homes = homes.filter(query문)
```
위와 같이 수정하였습니다 ! :+1:

2021-01-04 14:29 UTC, seungjaekim-git commented on homes/views.py
> +            homes  = homes.filter(query3)
넵 ! 이 부분도 불필요하게 query에 담아서 필터링을 하고 있었네요. 바로 filter에 넣어서 필터링 하겠습니다 !

2021-01-04 15:01 UTC, seungjaekim-git commented on homes/views.py
> +            homes = homes.filter(facility=facility)
먼저 ! facilities는 숙소의 편의시설을 나타내는데, 하나의 숙소가 여러개의 편의시설을 가지고있고, 유저가 여러개의 편의시설을 선택했을때, 해당 편의시설을 "모두"충족하는 숙소만을 필터링할려고 합니다.  

하지만, 여기서 "facility__in"을 하게되면 유저가 선택한 편의시설 중 "하나"라도 충족하면 제외되기 않기 때문에 제가 바라는 방향으로 데이터를 필터링할 수 가없었습니다.

그렇기 때문에, 선택된 편의시설을 모두 검사해서 하나의 숙소가 "모든" 편의 시설을 충족할 수 있게 계속 필터 채인을 걸었습니다.

SQL 문도 제가 원하는 방향으로 계속 옵션을 추가하는 식으로 했습니다. :+1: 
```sql
WHERE (`home_facilities`.`facility_id` = 1 AND T4.`facility_id` = 2 AND T6.`facility_id` = 3 AND T8.`facility_id` = 4 AND T10.`facility_id` = 5 AND ...
```

참고한 자료 : [스택오버플로우 링크](https://stackoverflow.com/questions/8618068/django-filter-queryset-in-for-every-item-in-list)

2021-01-05 14:16 UTC, ulfrid requested changes

2021-01-05 14:16 UTC, ulfrid commented on homes/views.py
> +                user_id  = 1,
고정 값을 넣은 이유가 있나요?

2021-01-05 14:33 UTC, seungjaekim-git commented on homes/views.py
> +                user_id  = 1,
이 부분은 나중에 로그인체크 데코레이터가 추가되면 request.user에 저장된 user id로 대체된 부분이여서 남겨두었습니다 ! 일단 테스트를 위해서 1번을 사용하였습니다 !

2021-01-05 14:34 UTC, seungjaekim-git commented on homes/views.py
> +                user_id  = 1,
추가적으로 제 숙소 리스트에는 유저가 로그인할 시, 자신이 북마크해둔 숙소에 따로 Boolean값을 표시할 것이기 때문에 아마 마지막으로 merge될것같습니다 ㅠ

2021-01-05 14:36 UTC, ulfrid commented on homes/views.py
> +                user_id  = 1,
음 그렇군요 그럼 그때까지 머지는 어렵겠네요

2021-01-06 05:26 UTC, ulfrid commented
LGTM.

2021-01-06 05:26 UTC, merged