add :: 예약 등록/리스트/디테일 구현
wecode-bootcamp-korea/15-2nd-CodeBnB-backend pull request #5
Opened 2021-01-04 02:45 UTC by dltngks54

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)

숙소 예약 관련하여 예약 등록 / 예약 리스트 조회 (예정된 예약, 이미 사용한 숙소, 취소된 예약)  
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

숙소 예약 등록**: 아직 유저를 식별하는 토큰이 없어 임시로 db에 유저를 가져와 view를 작성하였습니다. 
Guest 테이블에 성인,어린이,유아가 생성이 되어 있고, 인원수는 ReservationGuest라는 중간 테이블에 속해 있습니다.
 (결제는 진행 하지 않지만 모델링을 할때 Payment 라는 사용자의 카드정보를 담는 테이블을 생성하여서 bcrypt로 암호화 하였습니다. 추후 모델링 리뷰를 통해 사용자의 카드정보는 모델링을 하지 않는 것이라고 전달받았습니다.)

 
             

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-05 01:53 UTC, jamessoun93 requested changes

2021-01-05 01:53 UTC, jamessoun93 commented on reservations/views.py
> +    def post(self, request):
`ReservationListView` 라는 이름의 `View` 클래스랑은 어울리지 않는 `POST` 기능이 들어있는데 확인 후 수정 부탁드리겠습니다.

2021-01-05 01:53 UTC, jamessoun93 commented on reservations/tests.py
> +        client = Client()
Client 인스턴스를 매 메소드마다 만들어주시는것보다 최초 1회 생성해주신 후 해당 인스턴스를 재사용하는 방법으로 구현해주시는게 더 효율적입니다! 수정해보세요!

2021-01-05 02:04 UTC, jamessoun93 requested changes

2021-01-05 02:04 UTC, jamessoun93 commented on reservations/views.py
> +            hash_total_cost = hash_total_cost.decode('utf-8')
`total_cost` 를 암호화해주시는 이유가 있을까요?!?

2021-01-05 02:04 UTC, jamessoun93 commented on reservations/views.py
> +            )
새로운 `Payment` 를 생성한 뒤 예약 단계에서 에러가 발생하여 끊기게 된다면 어떻게 될까요? 이 문제를 해결할 수 있는 방법에 대해서 한번 알아보시고 코멘트 남겨주세요!

2021-01-05 02:10 UTC, jamessoun93 requested changes

2021-01-05 02:10 UTC, jamessoun93 commented on reservations/views.py
> +                "home__home_host",
`home__` 만으로 `home` 은 함께 가져오게되어서 `home` 은 따로 필요하지 않습니다~

2021-01-05 04:39 UTC, dltngks54 commented on reservations/views.py
> +            )
Payment 를 생성하고 예약단계에서 에러가 발생하면 유저가 입력한 Payment의 정보만 홀로 db에 저장 되는 문제를 확인하였습니다... ㅠㅠ 
제가 원하는 것은! 객체를 생성하는 도중 단 하나라도 오류가 난다면 다른 객체들도 만들어지지 않는 것 입니다.
원하는 기능을 구현하기 위해 트랜잭션이라는 개념을 사용 하여 조치를 하였습니다.

2021-01-05 04:40 UTC, dltngks54 commented on reservations/tests.py
> +        client = Client()
수정하였습니다!

2021-01-05 04:42 UTC, dltngks54 commented on reservations/views.py
> +            hash_total_cost = hash_total_cost.decode('utf-8')
없습니다ㅠㅠ 같은 테이블의 컬럼이라는 이유로 실수 하였습니다.. 더 꼼꼼히 보면서 로직 짜겠습니다.

2021-01-05 04:45 UTC, dltngks54 commented on reservations/views.py
> +                "home__home_host",
감사합니다 !

2021-01-05 04:45 UTC, dltngks54 commented on reservations/views.py
> +    def post(self, request):
수정하였습니다!

2021-01-05 06:56 UTC, ulfrid requested changes

2021-01-05 06:56 UTC, ulfrid commented on reservations/views.py
> +            hash_card_holder = hash_card_holder.decode('utf-8')
암호화 시도는 좋은데. 실제로는 이렇게 하면 안되겠죠?? 복호화 되는 방식으로 저장해야합니다. 
지금 AES같은 양방향 모듈을 도입할 수 없다면~! jwt를 사용해서 해보는 건 어떨까요? 
payload에 값을 저장시키고 jwt로  암,복호화하는 겁니다.

2021-01-05 06:56 UTC, ulfrid commented on reservations/views.py
> +            hash_card_holder = hash_card_holder.decode('utf-8')
추가로 디코드 지정으로 재할당 하지말고 아래에 값을 저장시킬때 디코드 해주세요. 코드를 무려 5줄 줄일수 있군요~!

2021-01-05 07:49 UTC, dltngks54 commented on reservations/views.py
> +            hash_card_holder = hash_card_holder.decode('utf-8')
지훈님! 제가 지금 사용한 bcrypt는 암호화는 가능하지만 복호화가 힘들기 때문에 bcrypt 대신 jwt로 암호화 하시라는 말씀인가요?

2021-01-05 08:26 UTC, dltngks54 commented on reservations/views.py
> +            hash_card_holder = hash_card_holder.decode('utf-8')
jwt로 암호화 수정하였습니다!

2021-01-06 02:41 UTC, ulfrid commented
LGTM.

2021-01-06 02:41 UTC, merged