Add: 북마크(숙소좋아요) 등록, 삭제, 리스트 구현 완료 / 데코레이터 적용 예정
wecode-bootcamp-korea/15-2nd-CodeBnB-backend pull request #6
Opened 2021-01-05 20:26 UTC by markiron99

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 북마크 (숙소 좋아요) 등록, 삭제, 리스트 기능 구현(데코레이터 적용예정)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 북마크 (숙소 좋아요) 등록, 삭제, 리스트 기능 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-06 05:24 UTC, ulfrid requested changes
확인 부탁드립니다.

2021-01-06 05:24 UTC, ulfrid commented on bookmarks/views.py
> +                    }for home_price in home.homeprice_set.all() if home_price.price_category.name=="1박비용"],
```suggestion
                    }for home_price in home.homeprice_set.all() if home_price.price_category.name=="1박비용"],
```
1박비용이라는 가격 카테고리 일때만 이 내용이 나오게 되나요? 
이 조건을 애초에 컨트롤 할 수는 없나요?

2021-01-06 13:21 UTC, markiron99 commented on bookmarks/views.py
> +                    }for home_price in home.homeprice_set.all() if home_price.price_category.name=="1박비용"],
에어비앤비 북마크 리스트에 있는 숙소 가격은 1박 기준의 가격으로 노출되어있습니다.

그래서 if 문을 사용하여 1박 비용인 경우의 가격을 추출한 상황입니다..

2021-01-06 14:42 UTC, ulfrid commented on bookmarks/views.py
> +                    }for home_price in home.homeprice_set.all() if home_price.price_category.name=="1박비용"],
그럼 이렇게 하드코딩보다는 코드 상단에 상수로 선언하고, 상수를 할당해주세요.
```
    PRICE_CATEGORY_NAME = '1박비용'
```

2021-01-06 15:40 UTC, markiron99 commented on bookmarks/views.py
> +                    }for home_price in home.homeprice_set.all() if home_price.price_category.name=="1박비용"],
리뷰주신 부분 수정 반영 하도록 하겠습니다!

2021-01-07 02:04 UTC, ulfrid commented
LGTM.

2021-01-07 02:04 UTC, merged